# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'player.ui'
#
# Created: Thu Jul  9 01:39:06 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(640, 592)
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        MainWindow.setAutoFillBackground(True)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.playButton = QtGui.QPushButton(self.centralwidget)
        self.playButton.setGeometry(QtCore.QRect(320, 280, 99, 41))
        self.playButton.setObjectName("playButton")
        self.stopButton = QtGui.QPushButton(self.centralwidget)
        self.stopButton.setGeometry(QtCore.QRect(20, 240, 99, 41))
        self.stopButton.setObjectName("stopButton")
        self.exitButton = QtGui.QPushButton(self.centralwidget)
        self.exitButton.setGeometry(QtCore.QRect(20, 290, 99, 27))
        self.exitButton.setObjectName("exitButton")
        self.horizontalSlider = QtGui.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(140, 250, 471, 31))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.pictureLabel = QtGui.QLabel(self.centralwidget)
        self.pictureLabel.setGeometry(QtCore.QRect(30, 10, 581, 191))
        self.pictureLabel.setText("")
        self.pictureLabel.setPixmap(QtGui.QPixmap("pics/party.jpg"))
        self.pictureLabel.setScaledContents(True)
        self.pictureLabel.setObjectName("pictureLabel")
        self.listWidget = QtGui.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(20, 340, 581, 191))
        self.listWidget.setObjectName("listWidget")
        self.nowPlayingLabel = QtGui.QLabel(self.centralwidget)
        self.nowPlayingLabel.setGeometry(QtCore.QRect(140, 210, 471, 20))
        self.nowPlayingLabel.setText("")
        self.nowPlayingLabel.setObjectName("nowPlayingLabel")
        self.prevButton = QtGui.QPushButton(self.centralwidget)
        self.prevButton.setGeometry(QtCore.QRect(250, 280, 51, 41))
        self.prevButton.setObjectName("prevButton")
        self.nextButton = QtGui.QPushButton(self.centralwidget)
        self.nextButton.setGeometry(QtCore.QRect(440, 280, 51, 41))
        self.nextButton.setObjectName("nextButton")
        self.repeatCheckBox = QtGui.QCheckBox(self.centralwidget)
        self.repeatCheckBox.setEnabled(False)
        self.repeatCheckBox.setGeometry(QtCore.QRect(530, 240, 81, 22))
        self.repeatCheckBox.setObjectName("repeatCheckBox")
        self.randomCheckBox = QtGui.QCheckBox(self.centralwidget)
        self.randomCheckBox.setEnabled(False)
        self.randomCheckBox.setGeometry(QtCore.QRect(440, 240, 81, 22))
        self.randomCheckBox.setObjectName("randomCheckBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuPlaylist = QtGui.QMenu(self.menubar)
        self.menuPlaylist.setObjectName("menuPlaylist")
        self.menu_Sort_by = QtGui.QMenu(self.menuPlaylist)
        self.menu_Sort_by.setObjectName("menu_Sort_by")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_Open = QtGui.QAction(MainWindow)
        self.action_Open.setObjectName("action_Open")
        self.action_Quit = QtGui.QAction(MainWindow)
        self.action_Quit.setObjectName("action_Quit")
        self.actionShuffle = QtGui.QAction(MainWindow)
        self.actionShuffle.setObjectName("actionShuffle")
        self.actionFilename = QtGui.QAction(MainWindow)
        self.actionFilename.setCheckable(True)
        self.actionFilename.setObjectName("actionFilename")
        self.actionTitle = QtGui.QAction(MainWindow)
        self.actionTitle.setCheckable(True)
        self.actionTitle.setObjectName("actionTitle")
        self.actionArtist = QtGui.QAction(MainWindow)
        self.actionArtist.setCheckable(True)
        self.actionArtist.setObjectName("actionArtist")
        self.actionGenre = QtGui.QAction(MainWindow)
        self.actionGenre.setCheckable(True)
        self.actionGenre.setObjectName("actionGenre")
        self.actionYear = QtGui.QAction(MainWindow)
        self.actionYear.setCheckable(True)
        self.actionYear.setObjectName("actionYear")
        self.actionRepeat = QtGui.QAction(MainWindow)
        self.actionRepeat.setCheckable(True)
        self.actionRepeat.setObjectName("actionRepeat")
        self.actionClear = QtGui.QAction(MainWindow)
        self.actionClear.setObjectName("actionClear")
        self.menuFile.addAction(self.action_Open)
        self.menuFile.addAction(self.action_Quit)
        self.menu_Sort_by.addAction(self.actionFilename)
        self.menu_Sort_by.addAction(self.actionTitle)
        self.menu_Sort_by.addAction(self.actionArtist)
        self.menu_Sort_by.addAction(self.actionGenre)
        self.menu_Sort_by.addAction(self.actionYear)
        self.menuPlaylist.addAction(self.menu_Sort_by.menuAction())
        self.menuPlaylist.addAction(self.actionShuffle)
        self.menuPlaylist.addAction(self.actionRepeat)
        self.menuPlaylist.addAction(self.actionClear)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuPlaylist.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "pyLex ", None, QtGui.QApplication.UnicodeUTF8))
        self.playButton.setText(QtGui.QApplication.translate("MainWindow", "Play", None, QtGui.QApplication.UnicodeUTF8))
        self.stopButton.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.exitButton.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.prevButton.setText(QtGui.QApplication.translate("MainWindow", "<<", None, QtGui.QApplication.UnicodeUTF8))
        self.nextButton.setText(QtGui.QApplication.translate("MainWindow", ">>", None, QtGui.QApplication.UnicodeUTF8))
        self.repeatCheckBox.setText(QtGui.QApplication.translate("MainWindow", "repeat", None, QtGui.QApplication.UnicodeUTF8))
        self.randomCheckBox.setText(QtGui.QApplication.translate("MainWindow", "random", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPlaylist.setTitle(QtGui.QApplication.translate("MainWindow", "&Playlist", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Sort_by.setTitle(QtGui.QApplication.translate("MainWindow", "Sort by", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Open.setText(QtGui.QApplication.translate("MainWindow", "&Open", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Quit.setText(QtGui.QApplication.translate("MainWindow", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShuffle.setText(QtGui.QApplication.translate("MainWindow", "&Shuffle", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFilename.setText(QtGui.QApplication.translate("MainWindow", "Filename", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTitle.setText(QtGui.QApplication.translate("MainWindow", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.actionArtist.setText(QtGui.QApplication.translate("MainWindow", "Artist", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGenre.setText(QtGui.QApplication.translate("MainWindow", "Genre", None, QtGui.QApplication.UnicodeUTF8))
        self.actionYear.setText(QtGui.QApplication.translate("MainWindow", "Year", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRepeat.setText(QtGui.QApplication.translate("MainWindow", "&Repeat", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClear.setText(QtGui.QApplication.translate("MainWindow", "&Clear", None, QtGui.QApplication.UnicodeUTF8))

